# Generated by Django 2.0.1 on 2018-03-13 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.DateField(default=3, verbose_name='Month')),
                ('actual_amount', models.IntegerField(default=0, max_length=100000)),
                ('amount_spent', models.IntegerField(default=0, max_length=100000)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('mobile_number', models.IntegerField(max_length=15)),
            ],
        ),
    ]
