# Generated by Django 2.0.1 on 2018-03-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20180313_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='mobile_number',
            field=models.IntegerField(default='#', max_length=15),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.CharField(default='Unnamed', max_length=30),
        ),
    ]
