# Generated by Django 2.0.1 on 2018-03-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20180315_2241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='actual_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='month',
            name='amount_spent',
            field=models.IntegerField(default=0),
        ),
    ]
