# Generated by Django 2.0.1 on 2018-03-17 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_month_spentlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='SpentList',
        ),
    ]
