# Generated by Django 2.0.1 on 2018-03-17 11:03

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_month_spentlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='SpentList',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
