# Generated by Django 2.0.1 on 2018-03-17 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_month_spentlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_name',
            field=models.IntegerField(default=3, verbose_name='Month'),
        ),
    ]
