# Generated by Django 2.0.1 on 2018-03-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20180317_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='month_name',
            field=models.IntegerField(default=3),
        ),
    ]
