# Generated by Django 2.0.1 on 2018-03-18 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_auto_20180317_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='SpentList',
            new_name='spent_list',
        ),
        migrations.AlterField(
            model_name='month',
            name='month_name',
            field=models.IntegerField(default=3, verbose_name='Month'),
        ),
    ]
