# Generated by Django 2.0.1 on 2018-03-18 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20180318_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 10, 59, 12, 97595)),
        ),
    ]
