# Generated by Django 2.0.1 on 2018-03-18 06:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_month_modified_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='month',
            name='modified_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 3, 18, 12, 7, 11, 936558)),
        ),
    ]
