# Generated by Django 2.0.1 on 2018-03-18 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20180318_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='month',
            name='modified_date',
        ),
    ]
