# Generated by Django 2.0.1 on 2018-03-18 10:52

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20180318_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='month',
            old_name='spent_list',
            new_name='common_money',
        ),
        migrations.AddField(
            model_name='month',
            name='user_spent_list',
            field=picklefield.fields.PickledObjectField(default=1, editable=False),
            preserve_default=False,
        ),
    ]
